# Generated by Django 2.1.3 on 2018-12-05 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteChequeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('presion_arterial', models.DecimalField(decimal_places=0, max_digits=3, max_length=5)),
                ('ritmo_cardiaco', models.DecimalField(decimal_places=0, max_digits=3, max_length=5)),
                ('observacion', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('documento', models.DecimalField(decimal_places=0, default=0, max_digits=6, max_length=5)),
                ('apellido', models.CharField(max_length=200)),
                ('edad', models.DecimalField(decimal_places=0, default=0, max_digits=3, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.CharField(max_length=10)),
                ('min', models.DecimalField(decimal_places=0, max_digits=3, max_length=5)),
                ('max', models.DecimalField(decimal_places=0, max_digits=3, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Enfermero',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Persona')),
                ('piso', models.CharField(max_length=200)),
                ('turno', models.CharField(max_length=20)),
            ],
            bases=('app.persona',),
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Persona')),
                ('sala', models.CharField(max_length=20)),
            ],
            bases=('app.persona',),
        ),
        migrations.CreateModel(
            name='PresionSanguinea',
            fields=[
                ('rango_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Rango')),
            ],
            bases=('app.rango',),
        ),
        migrations.CreateModel(
            name='RitmoCardiaco',
            fields=[
                ('rango_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Rango')),
            ],
            bases=('app.rango',),
        ),
        migrations.AddField(
            model_name='pacientechequeo',
            name='enfermero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Enfermero'),
        ),
        migrations.AddField(
            model_name='pacientechequeo',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Paciente'),
        ),
    ]
